### ISSUE TITLE
Questions about MMVC_Trainer

### ISSUE THREAD

**Issue by Ishihara-Masabumi** [isletennos/MMVC_Trainer#111]
I have some questions about MMVC_Trainer.

(1) G_180000.pth and D_180000.pth
In the fine_model, there are G_180000.pth and D_180000.pth model files.
What is G_180000.pth for?
What is D_180000.pth for?

(2) G_latest_99999999.pth and D_latest_99999999.pth
In the logs/20220306_24000, there are G_latest_99999999.pth and D_latest_99999999.pth model files.
What kind of training is done for G_latest_99999999.pth?
What kind of training is done for D_latest_99999999.pth?

**Comment by isletennos** [comment]
I apologize for the delay.
(1)
MMVC is a VC model based on VITS. 
G stands for Generator, and D stands for Discriminator.
G_180000.pth and D_180000.pth are pre-trained models.
Based on these models, fine-tuning is performed using the source speaker's voice data and the target speaker's voice.

(2)
G_latest_99999999.pth and D_latest_99999999.pth being the most recent models saved at the intervals specified in the config file.
Is the answer provided addressing the intention of your question？

**Comment by Ishihara-Masabumi** [comment]
The most recent models saved, OK
