### ISSUE TITLE
Dockerfileがあったらいただけるとありがたいです

### ISSUE THREAD

**Issue by TMNTmaker** [isletennos/MMVC_Trainer#84]
すばらしいプロジェクトを公開してくださりありがとうございます！

WSL2+Dockerで学習してみたいので、もし既に作成済みのDockerfileをお持ちでしたら、共有していただくことは可能でしょうか？

よろしくお願いいたします！

**Comment by isletennos** [comment]
ありがとうございます！
すみません、現在作成済みのDockerfileはないです。申し訳ないです……。
google colab の制限が厳しくなってきた背景もあり、次のver以降はdocker fileの配布も検討しております。
(年内に次のverを公開予定なので、今のverのdocker fileを私の方から作って配布といったことは予定していないです)

**Comment by TMNTmaker** [comment]
早速のご返信ありがとうございます！
承知しました。では次のアップデートを楽しみにしております。
ありがとうございました。
